language: python

python:
  - 3.6

install:
  - pip install codecov
  - pip install -r requirements/dev.txt

before_script:
  - flake8 .

script:
  - coverage run src/manage.py test
  - coverage report

after_success:
  - codecov

notifications:
  email: false
  webhooks:
    urls:
      - GITTER_WEBHOOK_URL
    on_success: change
    on_failure: always
    on_start: never
